gdrive_credentials: "None"
gdrive_directory: "None"
detection_max_frame_length: 50
detection_frame_buffer: 5
results_dir: "res"

yolo_weights: "very-good-best.pt"
ocr_weights: "best_acc_300k_90percent"
write_to_db: False

rename_lp_image: True